blog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from blog.models import Blog

urlpatterns = patterns("",
        #url(r"^$", 'blog.views.index', name='index'), 
        url(r"^$", ListView.as_view(queryset=Blog.objects.all(), context_object_name="blogs", template_name="blog/index.html"), name="index"),
        url(r"^(?P<pk>\d+)/detail/$", DetailView.as_view(model=Blog, template_name="blog/blog_detail.html", context_object_name="blog"), name="detail"),
        )

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
)

blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add = True)
    category = models.ManyToManyField(Category)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering=["-timestamp", "title"]

blog/views.py
from django.shortcuts import render
#from blog.models import Blog, Category
#from django.http import HttpResponse

# Create your views here.
#def index(request):
    ##return HttpResponse("Hello, world")
    #blogs = Blog.objects.all()
    #return render(request, "blog/index.html", locals())

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block TITLE %} {% endblock %}</title>

    <!-- Bootstrap -->
	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<div class="container">
		{% block BODY %}
		{% endblock %}
	</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

blog/templates/blog/blog_detail.html
{% extends "blog/base.html" %}

{% block TITLE %} WeiHu's Blog {% endblock %}

{% block BODY %}
<h1>{{ blog.title }} </h1>
<p>{{ blog.content|safe }}</p>
<p>{{ blog.timestamp|date:"Y-m-d H:m:s" }}</p>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block TITLE %} WeiHu's Blog {% endblock %}

{% block BODY %}
{% for blog in blogs %}
<a href="{% url "blog:detail" blog.id %}"> <h3>{{ blog.title }}</h3> </a>
{% empty %}
No blog in here.
{% endfor %}
<!--{% url "blog:index" %}-->
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block TITLE %} WeiHu's Blog {% endblock %}

{% block BODY %}
{% for blog in blogs %}
<h1>{{ blog.title }}</h1>
<p>{{ blog.content|safe }}</p>
<p>{{ blog.timestamp|date:"Y-m-d H:m:s" }}</p>
{% empty %}
No blog in here.
{% endfor %}
{% endblock %}